name: drought_mobile_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.3+4
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  webview_flutter: ^2.8.0
  sizer: ^2.0.15
  image_picker: ^1.0.2
  geolocator: ^10.0.0
  get: ^4.6.5
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  device_info_plus: ^9.0.3
  package_info_plus: ^4.2.0
  http: ^1.1.0
  modal_progress_hud_nsn: ^0.4.0
  shimmer: ^3.0.0
  connectivity_plus: ^4.0.2
  path_provider: ^2.1.1
  hive: ^2.2.3
  upgrader: ^8.1.0
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # Replace with the path to your icon image
  adaptive_icon_background: "#FFFFFF"  # Background color for Android Adaptive Icon
  adaptive_icon_foreground: "assets/icon/icon.png"  # Icon foreground for Android Adaptive Icon
  image_path_ios: "assets/icon/icon.png"  # iOS icon (if different)
  android_icons:
    - name: "ic_launcher"
      adaptive_icon_background: "#FFFFFF"  # Background color for Android Launcher Icon
      adaptive_icon_foreground: "assets/icon/icon.png"  # Icon foreground for Android Launcher Icon
      playstore: true  # Generate an icon for the Play Store listing
  ios_icons:
    - name: "AppIcon"  # iOS AppIcon is a required name
      sizes:
        - 120x120
        - 180x180
        - 1024x1024
      unselected_sizes:
        - 30x30
      ios_image: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
